# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'The Cake is a lie'

style: dark # dark (default) or light

plugins:
  - jekyll-seo-tag

theme: jekyll-theme-minimal
